COIN_0_SYMBOL = "OSC"
COIN_0_NAME = "OpenSourceCoin"
COIN_0_TOKEN = ""
COIN_0_HOST = "127.0.0.1"
COIN_0_PORT = 
COIN_0_USER = ""
COIN_0_PASS = ""
COIN_0_BALANCE = True

COIN_1_SYMBOL = "FRK"
COIN_1_NAME = "Franko"
COIN_1_TOKEN = ""
COIN_1_HOST = "127.0.0.1"
COIN_1_PORT = 
COIN_1_USER = ""
COIN_1_PASS = ""
COIN_1_BALANCE = True

